/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,ts}'],
  theme: {
    extend: {
      colors: {
        surface: '#fff4f0',
        background: '#fff4f0',
        'surface-container': '#ffece6',
        'surface-container-low': '#fff9f5',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#ffe2d9',
        'surface-container-highest': '#ffd9ce',
        'surface-variant': '#ffe0d6',
        'surface-bright': '#fff4f0',
        'surface-dim': '#e8d3cb',
        'on-surface': '#33130f',
        'on-primary': '#ffffff',
        'on-secondary': '#ffffff',
        primary: '#b03a48',
        'primary-container': '#ffd9d8',
        'on-primary-container': '#5c0912',
        'primary-fixed': '#ffd9d8',
        'primary-fixed-dim': '#ffb1b1',
        'on-primary-fixed': '#5c0912',
        'on-primary-fixed-variant': '#8c232f',
        secondary: '#8f4c48',
        'secondary-container': '#ffdad3',
        'on-secondary-container': '#5b1713',
        'secondary-fixed': '#ffdad3',
        'secondary-fixed-dim': '#ffb3aa',
        'on-secondary-fixed': '#5b1713',
        'on-secondary-fixed-variant': '#71332f',
        tertiary: '#725b20',
        'tertiary-container': '#ffdf95',
        'on-tertiary-container': '#4e3d00',
        'tertiary-fixed': '#ffdf95',
        'tertiary-fixed-dim': '#e9c054',
        'on-tertiary-fixed': '#4e3d00',
        'on-tertiary-fixed-variant': '#584401',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'on-background': '#33130f',
        'on-surface-variant': '#524341',
        outline: '#857370',
        'outline-variant': '#d8c2be',
        'inverse-surface': '#4b3532',
        'inverse-on-surface': '#ffece8',
        'inverse-primary': '#ffb1b1',
        'surface-tint': '#b03a48',
        glow: '#ff8a7a',
        blush: '#ffc2a8',
        rose: '#d96c6c',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'touch-target': '48px',
        gutter: '24px',
        unit: '8px',
        'container-max': '600px',
        'section-gap': '64px',
      },
      fontFamily: {
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-md': ['Playfair Display', 'serif'],
        'display-lg': ['Playfair Display', 'serif'],
        'display-lg-mobile': ['Playfair Display', 'serif'],
        'label-sm': ['Inter', 'sans-serif'],
        script: ['"Great Vibes"', 'cursive'],
        script2: ['"Dancing Script"', 'cursive'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md': ['26px', { lineHeight: '34px', fontWeight: '700' }],
        'display-lg': ['56px', { lineHeight: '64px', letterSpacing: '-0.015em', fontWeight: '800' }],
        'display-lg-mobile': ['38px', { lineHeight: '44px', letterSpacing: '-0.01em', fontWeight: '800' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.08em', fontWeight: '600' }],
        'script-3xl': ['44px', { lineHeight: '1.1', fontWeight: '500' }],
        'script-2xl': ['36px', { lineHeight: '1.15', fontWeight: '500' }],
        'script-xl': ['30px', { lineHeight: '1.2', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
